name = "openai-replicate-proxy"
main = "index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "openai-replicate-proxy"

[env.staging]
name = "openai-replicate-proxy-staging"

# Environment variables (set these using wrangler secret put)
# REPLICATE_API_TOKEN - Your Replicate API token
# PROXY_API_KEY - Your proxy API key for authentication

# Example wrangler commands:
# wrangler secret put REPLICATE_API_TOKEN
# wrangler secret put PROXY_API_KEY
